paths:
  # Вход → Выход для препроцессинга
  raw_music:      data/raw/music
  prepared_music: data/prepared/music

  raw_noise:      data/raw/noise
  prepared_noise: data/prepared/noise

  raw_speech:      data/raw/speech
  prepared_speech: data/prepared/speech
  # Папка со сценариями (yaml) и папка для финального датасета
  scenarios: scenarios
  output:   dataset
